### ISSUE TITLE
GCs do not appear to have position information

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#12]
From #6 

@JustasB it could well be the case that the GCs are not given explicit positions, though it does look like it from the movie [here](http://senselab.med.yale.edu/modeldb/data/151681/movie1.mp4)

![selection_026](https://cloud.githubusercontent.com/assets/1556687/12095783/f3225600-b308-11e5-9699-3d59f3deb2b2.png)

They may be just randomly positioned inside the main ellipsoid, but [this code](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NEURON/granules.py#L26) suggests otherwise... 

Note though that there is a dendrite on the GCs which isn't shown above.

Does the connectivity depend on the location of the GC?

Would be good to get Francesco to comment on this.

**Comment by JustasB** [comment]
This has been resolved. There is a lookup table and some functions that give the GC positions.

http://opensourcebrain.org/projects/d-olfactory-bulb-network/repository/revisions/master/show/NeuroML2/Networks?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FJustasB%2FMig3DTest%2Fmaster%2FNeuroML2%2FNetworks%2FBulb_5MC_240GC.net.nml
