### ISSUE TITLE
Create NML2/LEMS versions of synaptic mechanisms

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#13]
Following on from question in #6, there should be 2 synaptic connections per NEURON connection in the NML2 file if there is a functioning NetConn each way between the "pre" & "post" connection points.

@JustasB which mod file(s) are used for the synapses? [This](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NEURON/ampanmda.mod)? If so have a look at this LEMS file which could be adapted from [this combined AMPA/NMDA file](https://github.com/OpenSourceBrain/BlueBrainProjectShowcase/blob/master/NMC/NeuroML2/SynapseExample/detAMPANMDASynapse.xml). Making a combined synapse in LEMS like this would be slightly easier than repeating each connection with one AMPA and one NMDA in pure NML2.

**Comment by JustasB** [comment]
Yup, it uses that synapse 
[AmpaNmda](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NEURON/ampanmda.mod)

as well as:
[GranuleSpine](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/c15d316aa73be725a80ed67c7fe20f63d80294d0/NEURON/granule.hoc)
[ThreshDetect](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/c15d316aa73be725a80ed67c7fe20f63d80294d0/NEURON/ThreshDetect.mod)
[FastInhib](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/c15d316aa73be725a80ed67c7fe20f63d80294d0/NEURON/fi.mod)

What are your thoughts on handling the spine in NML? Should that be rolled into the synapse or separated out into another object? Let me know if you have a synapse with a spine example.

Below is the meat of where the synapse is constructed:
https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NEURON/mgrs.py
lines 99-115

```
    if self.msecden:
      self.md = h.ThreshDetect(self.msecden(xm))
      self.fi = h.FastInhib(self.msecden(xm))
      self.fi.gmax = params.inh_gmax
      self.fi.tau1 = params.fi_tau1
      self.fi.tau2 = params.fi_tau2
      pc.set_gid2node(self.md_gid, pc.id())
      pc.cell(self.md_gid, h.NetCon(self.md, None), 1)

    if self.gpriden:
      self.spine = h.GranuleSpine()
      self.spine.neck.connect(self.gpriden(xg))
      self.gd = h.ThreshDetect(self.spine.head(0.5))
      self.ampanmda = h.AmpaNmda(self.spine.head(0.5))
      self.ampanmda.gmax = params.exc_gmax
      pc.set_gid2node(self.gd_gid, pc.id())
      pc.cell(self.gd_gid, h.NetCon(self.gd, None), 1)
```

**Comment by pgleeson** [comment]
If the spine section gets connected to the existing Granule cell, I'd suspect that section gets exported into the GCxx.cell.nml file, as long as the export is done after the connections are made...

You could look in the ModelView for the simulation to see if they are there in the individual GCs...

**Comment by JustasB** [comment]
The syns have been converted and can be found under NeuroML2/Synapses.

**Comment by JustasB** [comment]
This has been done here: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/pull/25
