### ISSUE TITLE
Export or create NML2 cell file(s) for granule cell

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#15]
While Mitral cells are all different, it seems that the GCs are all the same (but probably positioned at different locations, see #12) 

If they are all the same, a single GC.cell.nml should suffice, otherwise the export script should be updated to handle these too.

Re the question here: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/issues/6#issuecomment-168417334, the numberInternalDivisions is equal to nseg, which can be set to any integer value >=1 independent of the number of points in the NEURON segment (which translate to segments in the segmentgroup in the exported NML). Usually for, e.g. a neurolucida reconstruction there will be many 3d points (~20) in a section, but only ~3 points required to evaluate v along it, so nseg =3.  

In the generated Mitral cells the number of 3D internal segments in the generated sections == nseg, probably just for convenience/a good approximation. This doesn't necessarily hold for the GC... Note this in the definition of GC: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NEURON/granule.hoc#L61

**Comment by JustasB** [comment]
The script for exporting GCs is now under Python/Export/export_granule.py

**Comment by JustasB** [comment]
This has been implemented here: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/pull/25
