### ISSUE TITLE
Visualise/verify network connectivity as exported in NML2

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#16]
Issue https://github.com/OpenSourceBrain/redmine/issues/245 should be resolved now...

First requirement with all of this is making sure the network is valid... Could you commit an example of the exported network if you're still having problems @JustasB?

**Comment by JustasB** [comment]
@pgleeson Ok, take a look at this net
https://github.com/JustasB/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NeuroML2/Networks/Bulb_2MC_20GC.net.nml

It validates with jnml -validate (at least locally). Don't know if this will show at all, as I haven't gotten nC to run yet.

**Comment by pgleeson** [comment]
One issue with nC is that you'd have to manually import all of the Mitral/GC cells to the nc project to be able to visualise a network with connections... The command line import needs work: https://github.com/NeuralEnsemble/neuroConstruct/issues/47

Better in the shorter term is the OSB visualisation option or the SVG export.

To allow you to test the visualisation of networks and cells (I see you've restructured the nml2 files in your fork) you could add a new OSB project and point it at your fork on github. Then you would be able to visualise any *.nml cels in the drop down menus in OSB 3D explorer

Note this however: https://github.com/openworm/org.geppetto/issues/463

**Comment by JustasB** [comment]
Ok, got it into a private OSB project. When I load it in the 3d explorer, it just spins the star icon saying it's taking longer than usual. Console is frozen, so don't know if there are any errors.

http://opensourcebrain.org/projects/d-olfactory-bulb-network?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FJustasB%252FMig3DTest%252Fmaster%252FNeuroML2%252FNetworks%252FBulb_2MC_20GC.net.nml#

I'll mess with a bunch of different versions of the network to see if it will render.

**Comment by JustasB** [comment]
Ok jnml -svg is showing something:
![screen shot 2016-01-06 at 9 52 15 am](https://cloud.githubusercontent.com/assets/10732358/12148371/450e37c4-b45b-11e5-9b27-3459476a2f09.png)

I'll try a few more models

**Comment by adrianq** [comment]
@JustasB I have just had a look at your network. OSB Explorer is not able to reproduce the network because [you are using a ComponentType as the synapse](https://github.com/JustasB/Mig3DTest/blob/be8239f81adff74726231441385317344ba087cb/NeuroML2/Networks/Bulb_2MC_20GC.net.nml#L152). It should be a component instead. So the best option is probably to include another NeuroML file with the synapse (component) as we are doing [here](https://github.com/OpenSourceBrain/ACnet2/blob/master/neuroConstruct/generatedNeuroML2/MediumNet.net.nml#L20).

**Comment by JustasB** [comment]
@adrianq Thank you. Anyway to make that into an error message visible in the console? I don't want to take up your guys' time with small mistakes like that.

**Comment by pgleeson** [comment]
@JustasB Good point re that check. Would be better to put that in jnml -validate to catch such errors earlier. It had been mentioned here: https://github.com/NeuroML/org.neuroml.model/issues/12#issuecomment-143162308. 

I've just locally implemented that check (and others, e.g. component pointed to by population not found, which is also a problem with your file, Granule_0_92389 etc.). Will do some tests on other NML examples on OSB and commit in the next day or two...

**Comment by adrianq** [comment]
@JustasB you are right. This is something we should expose to the user but at the moment there is not an easy way to implement it. I will try to find a solution for the next release and let you know...

**Comment by JustasB** [comment]
Take a look at svg export with 100 mitrals and ~1000 granules

![screen shot 2016-01-06 at 11 43 45 am](https://cloud.githubusercontent.com/assets/10732358/12151138/d858cfd0-b46a-11e5-94a2-43cf289927d6.png)

**Comment by pgleeson** [comment]
Nice... I think what's happening though is the somas of the mitral cells are already in place, i.e. not at (0,0,0), but you're positioning them at that location, i.e. they're being shifted twice. Try using 

```
 <location x="0" y="0" z="0"/>
```

Also a nice tool to try is  pynml-povray in pyNeuroML. You can even make movies...

**Comment by JustasB** [comment]
OK, here is the full mitral cell set (635) with ~1000 granules. This is with mitral location xyz=0 

![screen shot 2016-01-06 at 4 37 56 pm](https://cloud.githubusercontent.com/assets/10732358/12158103/1c851dd4-b494-11e5-81d6-588c7a7e8637.png)

**Comment by scrook** [comment]
Beautiful!

**Comment by pgleeson** [comment]
@JustasB updates to validator mentioned above have been committed, you'll get them if you pull & build jNeuroML from source again (python getNeuroML.py development).

**Comment by JustasB** [comment]
@pgleeson Got Gepetto to visualize a small exported network

http://opensourcebrain.org/projects/d-olfactory-bulb-network/repository/revisions/master/show/NeuroML2/Networks?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FJustasB%2FMig3DTest%2Fmaster%2FNeuroML2%2FNetworks%2FBulb_2MC_20GC.net.nml

**Comment by JustasB** [comment]
@pgleeson Is there any way to specify the orientation of the cells? For example in the above network, all the gran cells are pointing in one direction. Do you have any examples of setting the orientation of the cell, or does it all have to be done via the segment positions in the cell definition?

**Comment by pgleeson** [comment]
Currently, there is no way to (re)orient the cells in a population. This is part of the long term plans for nml2, but won't be there any time soon. I see you have done the next best thing currently available and exported an instance of each Grc & included those. Looks good.

**Comment by JustasB** [comment]
The verified connectivity has been implemented here: This has been implemented here: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/pull/25
