### ISSUE TITLE
cell with multiple specificCapacitances OR directly connect segments of different cells together

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#17]
In this model, there is one hoc definition for granule cells and one for GranuleSpine. Instances of each are later connected together directly at a specific location along a segment of the GC. The GC has cm of 4 and Spine has cm of 1. 

In NeuroML, I cannot find a way to have a cell have more than one specCap value, nor can I find a way to connect segments of different cells directly either. @pgleeson What's the best route here?

Both definitions are in this file: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NEURON/granule.hoc

The direct connection is made here: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/c15d316aa73be725a80ed67c7fe20f63d80294d0/NEURON/mgrs.py#L110

**Comment by pgleeson** [comment]
There's no way to connect electrically segments in different cells (well there is now, with gap junctions/analogue synapses but that's probably not the best approach).

It would be best to get these extra segs into the cells (e.g. with python), make a segmentGroup for them and then you should be able to set specCap on different regison with:

```
<specificCapacitance value="1.0 uF_per_cm2" segmentGroup="soma"/>
<specificCapacitance value="2.0 uF_per_cm2" segmentGroup="dend"/>
<specificCapacitance value="3.0 uF_per_cm2" segmentGroup="spines"/>
```

**Comment by JustasB** [comment]
Ok, I'll give the specCap per segmentGroup a try.
