### ISSUE TITLE
Python scripts for exporting Mitral/Granule cells should be (re)added

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#20]

**Comment by pgleeson** [comment]
Have noticed these here: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/NEURON/export_granule.py, but updated versions here: https://github.com/JustasB/Mig3DTest/blob/master/NEURON/export_granule.py...

**Comment by JustasB** [comment]
There are now under Python/Export folder

**Comment by JustasB** [comment]
The export scripts (including network) have been consolidated from NEURON folder into Python/Export folder, with documentation in the /readme.md in this PR: https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/pull/25
