### ISSUE TITLE
Adding license info

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#31]
@JustasB I'm adding license info to a few of the OSB repos. Hope you don't mind if this is released under MIT license. Note the added point [there](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/LICENSE) (and in [CITATION.md](https://github.com/OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D/blob/master/CITATION.md)) that the code in the NEURON folders has the added requirement that the original ModelDB entry should be cited too if someone uses that code.

**Comment by JustasB** [comment]
Not a problem @pgleeson

**Comment by pgleeson** [comment]
Thanks!
