### ISSUE TITLE
Resolve issue of disconnected axon hillock

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/MiglioreEtAl14_OlfactoryBulb3D#7]
Each mitral cell has an axon hillock/initial segment which is not located near the cell soma:

![selection_796](https://cloud.githubusercontent.com/assets/1556687/11087047/ce24780e-884e-11e5-92c4-e8b70d7b50c2.jpg)

[3D view](http://www.opensourcebrain.org/projects/miglioreetal14_olfactorybulb3d/repository/revisions/master/show/NeuroML2?explorer=https%253A%252F%252Fraw.githubusercontent.com%252FOpenSourceBrain%252FMiglioreEtAl14_OlfactoryBulb3D%252Fmaster%252FNeuroML2%252FMitral_0_1.cell.nml#)

These could potentially be relocated/rotated to the correct location when the cells are converted to NML2.

**Comment by JustasB** [comment]
@pgleeson Any tips for how to visualize the mitral cell in NEURON ModelView?

**Comment by pgleeson** [comment]
Best to make a self-contained hoc file which calls mkmitral.py and other files as needed. Try to make this into a script to create one fully set up mitral cells with all params as would be used in the main sim, and this can be used for #4 and for visualising the cell.

**Comment by JustasB** [comment]
Moved the hillock and initialseg to be next to the soma

http://opensourcebrain.org/projects/d-olfactory-bulb-network/repository/revisions/master/show/NeuroML2/Networks?explorer=https%3A%2F%2Fraw.githubusercontent.com%2FJustasB%2FMig3DTest%2Fmaster%2FNeuroML2%2FNetworks%2FBulb_5MC_240GC.net.nml

**Comment by pgleeson** [comment]
Great. They're all still oriented the same direction, i.e. not in line with cell body, but this is relatively minor.
